name: build-vmware-desktop-autoscaler-utility
on:
  push:
    branches:
      - '*'
    tags:
      - '!*'
    paths-ignore:
      - '**.yml'

  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GOPRIVATE: github.com/Fred78290/kubernetes-desktop-autoscaler
  GIT_PAT: ${{ secrets.GIT_PAT }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vendor
        uses: actions/cache@v3
        env:
          cache-name: cache-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name:  Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Build binary
        shell: bash
        run: |
          git config --global url.https://${GIT_PAT}:x-oauth-basic@github.com/.insteadOf https://github.com/
          make -e TAG=build-ci all

#  sonarcloud:
#    name: SonarCloud
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@v1.8

#      - name: Prepare SonarCloud
#        shell: bash
#        run: sudo chown -R $USER .scannerwork
