name: deploy-vmware-desktop-autoscaler-utility

on:
  push:
    tags:
      - v*
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_PAT: ${{ secrets.GIT_PAT }}
  GOPRIVATE: github.com/Fred78290/kubernetes-desktop-autoscaler

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vendor
        uses: actions/cache@v3.0.11
        env:
          cache-name: cache-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name:  Setup Go environment
        uses:  actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Build
        id: build
        shell: bash
        run: |
          git config --global url.https://${GIT_PAT}:x-oauth-basic@github.com/.insteadOf https://github.com/
          VERSION=${GITHUB_REF#refs/tags/}
          make -e TAG="${VERSION}" all
          cp out/linux/amd64/vmware-desktop-autoscaler-utility vmware-desktop-autoscaler-utility-linux-amd64
          cp out/linux/arm64/vmware-desktop-autoscaler-utility vmware-desktop-autoscaler-utility-linux-arm64
          cp out/darwin/amd64/vmware-desktop-autoscaler-utility vmware-desktop-autoscaler-utility-darwin-amd64
          cp out/darwin/arm64/vmware-desktop-autoscaler-utility vmware-desktop-autoscaler-utility-darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prep.outputs.tag }}
          draft: false
          files: |
            vmware-desktop-autoscaler-utility-linux-amd64
            vmware-desktop-autoscaler-utility-linux-arm64
            vmware-desktop-autoscaler-utility-darwin-amd64
            vmware-desktop-autoscaler-utility-darwin-arm64
